// // Mocks generated by Mockito 5.4.2 from annotations
// // in maids_test/test/features/home_page/data/repository/dogs_repository_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i5;

// import 'package:maids_test/home_page/data/datasources/dogs_remote_data.dart'
//     as _i4;
// import 'package:maids_test/home_page/data/models/breeds_model.dart'
//     as _i2;
// import 'package:maids_test/home_page/data/models/dog_model.dart'
//     as _i3;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeBreedsModel_0 extends _i1.SmartFake implements _i2.BreedsModel {
//   _FakeBreedsModel_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeDogModel_1 extends _i1.SmartFake implements _i3.DogModel {
//   _FakeDogModel_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [DogsRemoteDataSource].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockDogsRemoteDataSource extends _i1.Mock
//     implements _i4.DogsRemoteDataSource {
//   MockDogsRemoteDataSource() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i5.Future<_i2.BreedsModel> fetchBreeds() => (super.noSuchMethod(
//         Invocation.method(
//           #fetchBreeds,
//           [],
//         ),
//         returnValue: _i5.Future<_i2.BreedsModel>.value(_FakeBreedsModel_0(
//           this,
//           Invocation.method(
//             #fetchBreeds,
//             [],
//           ),
//         )),
//       ) as _i5.Future<_i2.BreedsModel>);

//   @override
//   _i5.Future<_i3.DogModel> fetchDogsInfo(
//     String? imageNumber,
//     String? breed,
//     String? subBreed,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #fetchDogsInfo,
//           [
//             imageNumber,
//             breed,
//             subBreed,
//           ],
//         ),
//         returnValue: _i5.Future<_i3.DogModel>.value(_FakeDogModel_1(
//           this,
//           Invocation.method(
//             #fetchDogsInfo,
//             [
//               imageNumber,
//               breed,
//               subBreed,
//             ],
//           ),
//         )),
//       ) as _i5.Future<_i3.DogModel>);
// }
