// Mocks generated by Mockito 5.4.2 from annotations
// in maids_test/test/features/home_page/use_case/fetch_breeds_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:maids_test/core/error/failures.dart'
    as _i5;
import 'package:maids_test/home_page/data/models/dog_model.dart'
    as _i7;
import 'package:maids_test/home_page/domain/entities/breeds_entity.dart'
    as _i6;
import 'package:maids_test/home_page/domain/repositories/dogs_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DogsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDogsRepository extends _i1.Mock implements _i3.DogsRepository {
  MockDogsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.BreedsEntity>> fetchBreeds() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBreeds,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.BreedsEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.BreedsEntity>(
          this,
          Invocation.method(
            #fetchBreeds,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.BreedsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.DogModel>> fetchDogsInfo(
    String? imageNumber,
    String? breed,
    String? subBreed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDogsInfo,
          [
            imageNumber,
            breed,
            subBreed,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.DogModel>>.value(
            _FakeEither_0<_i5.Failure, _i7.DogModel>(
          this,
          Invocation.method(
            #fetchDogsInfo,
            [
              imageNumber,
              breed,
              subBreed,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.DogModel>>);
}
