// // Mocks generated by Mockito 5.4.2 from annotations
// // in maids_test/test/features/home_page/data/remote_data/dogs_remote_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;

// import 'package:maids_test/core/network_info/network_info.dart'
//     as _i5;
// import 'package:maids_test/core/remote_data_function/http_methods.dart'
//     as _i3;
// import 'package:http/http.dart' as _i2;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
//   _FakeResponse_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [HttpFunctions].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockHttpFunctions extends _i1.Mock implements _i3.HttpFunctions {
//   MockHttpFunctions() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i4.Future<_i2.Response> getMethod({
//     required String? url,
//     required String? baseurl,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getMethod,
//           [],
//           {
//             #url: url,
//             #baseurl: baseurl,
//           },
//         ),
//         returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
//           this,
//           Invocation.method(
//             #getMethod,
//             [],
//             {
//               #url: url,
//               #baseurl: baseurl,
//             },
//           ),
//         )),
//       ) as _i4.Future<_i2.Response>);
// }

// /// A class which mocks [NetworkInf].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockNetworkInf extends _i1.Mock implements _i5.NetworkInf {
//   MockNetworkInf() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   String get baseUrl => (super.noSuchMethod(
//         Invocation.getter(#baseUrl),
//         returnValue: '',
//       ) as String);

//   @override
//   _i4.Future<bool> get isConnected => (super.noSuchMethod(
//         Invocation.getter(#isConnected),
//         returnValue: _i4.Future<bool>.value(false),
//       ) as _i4.Future<bool>);
// }
